### ISSUE TITLE
libdl dependence not included in link

### ISSUE THREAD

**Issue by cferenba** [laristra/libristra#10]
I'm trying to build libristra on darwin with Lua enabled, and I get the link error shown below.  Apparently liblua.a has a dependence on libdl.so, but libdl.so isn't included on the link line, and I can't find any way to turn it on.  Any ideas?

```
[ 19%] Linking CXX executable ../../test/embedded/ristra_iua_utils
cd /home/cferenba/ngc/libristra/build/ristra/embedded && /projects/opt/centos7/cmake/3.7.1/bin/cmake -E cmake_link_script CMakeFiles/ristra_iua_utils.dir/link.txt --verbose=1
/projects/opt/centos7/gcc/6.4.0/bin/g++   -O3 -DNDEBUG   CMakeFiles/ristra_iua_utils.dir/test/lua_utils.cc.o CMakeFiles/ristra_iua_utils.dir/__/__/test/embedded/ristra_iua_utils_test-standard.cc.o  -o ../../test/embedded/ristra_iua_utils -Wl,-rpath,/home/cferenba/ngc/libristra/build -rdynamic ../../libgtest.so ../../libRistra.so -lpthread -lpython3.4m /projects/opt/centos7/lua/5.3.4/lib/liblua.a -lm 
/usr/bin/ld: /projects/opt/centos7/lua/5.3.4/lib/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [test/embedded/ristra_iua_utils] Error 1
make[2]: Leaving directory `/home/cferenba/ngc/libristra/build'
make[1]: *** [ristra/embedded/CMakeFiles/ristra_iua_utils.dir/all] Error 2
make[1]: Leaving directory `/home/cferenba/ngc/libristra/build'
make: *** [all] Error 2
```

**Comment by charest** [comment]
This looks more like linking to liblua.a built using an older version of gcc.  In any event, see https://stackoverflow.com/questions/1274529/building-project-involving-cmake-how-do-i-make-it-aware-of-libraries#8243870

**Comment by cferenba** [comment]
@charest - Thanks for the stackoverflow link.  I followed it and now the build works and the tests pass.  I'll put in a PR with this fix shortly.
As for the gcc versions, I don't think that's an issue for this particular library.  It's just a thin C API wrapper around the Lua interpreter, so probably few if any calls to gcc-specific libs.

**Comment by charest** [comment]
OK.  Glad you fixed it.

**Comment by cferenba** [comment]
#11 contains the fix.
