### ISSUE TITLE
Lua 5.2 on HPC?

### ISSUE THREAD

**Issue by cmsquared** [laristra/libristra#24]
I'm trying to build with Lua support on our HPC machines at LANL.  I've not been able to find a version of Lua that is new enough.  Do we have one stashed somewhere, or should I roll my own in /usr/projects?

**Comment by charest** [comment]
You are going to have to build your own I think

**Comment by cferenba** [comment]
We could look into adding lua to the user_contrib builds.

**Comment by cmsquared** [comment]
I'm looking into building out a module for all of this.  Even to play with flecsi-sp, one needs a C++17 compiler (only one I found on HPC was gcc 7.3 in friendly_testing), Boost 1.58 (newer versions exists in user_contrib, but not built with gcc 7.3), Lua 5.2 (can't find anywhere), and a couple other things I've run into that I'm forgetting...

**Comment by cmsquared** [comment]
Oh, and I had to turn off caliper and HPX in the third party libs because of challenges of building there...

**Comment by cferenba** [comment]
"one needs a C++17 compiler..."
It's possible that Intel 19 beta would also work (available in friendly-testing).  It's on my to-do list to try this.  There exists at least one needed C++17 feature that Intel 18 is missing and Intel 19 has (according to Intel's documentation).

**Comment by cmsquared** [comment]
Ah, I had tried 18 and ran into the failure you mentioned.  I didn't notice the 2019.beta version.
